AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SORACOM CLI Lambda Function

Parameters:
  SoracomAuthKeySecretArn:
    Type: String
    Description: Secrets Manager secret ARN of SORACOM auth key
  FunctionName:
    Type: String
    Description: Function name
    Default: "soracom-cli"
  SoracomCliVersion:
    Type: String
    Description: SORACOM CLI version
    Default: "0.14.0"
  TimeoutInSeconds:
    Type: Number
    Description: Timeout in seconds
    Default: 60
    MinValue: 1
    MaxValue: 900
  LogRetentionInDays:
    Type: Number
    Description: Log retention (days)
    Default: 7
    AllowedValues:
      [
        1,
        3,
        5,
        7,
        14,
        30,
        60,
        90,
        120,
        150,
        180,
        365,
        400,
        545,
        731,
        1827,
        3653,
      ]

Globals:
  Function:
    Handler: main
    Runtime: go1.x
    Timeout: !Ref TimeoutInSeconds
    AutoPublishAlias: latest

Resources:
  SoracomFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: ./
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:DescribeSecret
                - secretsmanager:GetSecretValue
              Resource: !Ref SoracomAuthKeySecretArn
      Layers:
        - !Sub
          - arn:aws:lambda:ap-northeast-1:717257875195:layer:soracom-cli-${Version}:1
          - { Version: !Join ["", !Split [".", !Ref SoracomCliVersion]] }
      Environment:
        Variables:
          SORACOM_AUTH_KEY_SECRET_ARN: !Ref SoracomAuthKeySecretArn
          SORACOM_AUTH_KEY_ID: ""
          SORACOM_AUTH_KEY: ""

  SoracomFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SoracomFunction}
      RetentionInDays: !Ref LogRetentionInDays
